-- Generated by scripts/dump_schema.py from storage/db.py. Do not edit by hand;
-- run `python scripts/dump_schema.py` after changing the schema.

-- ==== history.sqlite ========================================================

CREATE TABLE messages (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    guild_id      TEXT,
    channel_id    TEXT NOT NULL,
    user_id       TEXT NOT NULL,
    user_name     TEXT,
    is_dm         INTEGER NOT NULL DEFAULT 0,
    content       TEXT NOT NULL,
    created_at    TEXT NOT NULL,
    indexed_at    TEXT,
    deleted       INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX idx_messages_channel_time ON messages(channel_id, created_at);

CREATE INDEX idx_messages_unindexed ON messages(indexed_at) WHERE indexed_at IS NULL;

CREATE INDEX idx_messages_user ON messages(user_id);

-- ==== app.sqlite ============================================================

CREATE TABLE activity_traces (
    user_id         TEXT PRIMARY KEY,
    display_name    TEXT,
    first_activity  TEXT,
    last_activity   TEXT,
    message_count   INTEGER NOT NULL DEFAULT 0,
    forgotten_at    TEXT NOT NULL
);

CREATE TABLE channel_modes (
    channel_id    TEXT PRIMARY KEY,
    mode          TEXT NOT NULL DEFAULT 'listen',
    updated_at    TEXT NOT NULL
);

CREATE TABLE channel_todos (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    channel_id    TEXT NOT NULL,
    body          TEXT NOT NULL,
    status        TEXT NOT NULL DEFAULT 'todo',
    created_at    TEXT NOT NULL,
    updated_at    TEXT NOT NULL
);

CREATE TABLE confidences (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    trammer_id    TEXT NOT NULL,
    content       TEXT NOT NULL,
    created_at    TEXT NOT NULL,
    FOREIGN KEY (trammer_id) REFERENCES trammers(discord_user_id)
);

CREATE TABLE echoes (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    trammer_id    TEXT NOT NULL,
    source_id     TEXT,
    match_type    TEXT NOT NULL,
    summary       TEXT NOT NULL,
    read          INTEGER DEFAULT 0,
    created_at    TEXT NOT NULL
);

CREATE TABLE entities (
    id            TEXT PRIMARY KEY,
    kind          TEXT NOT NULL,
    owner_id      TEXT NOT NULL,
    title         TEXT NOT NULL,
    description   TEXT,
    phase         TEXT DEFAULT 'draft',
    transparency  REAL DEFAULT 0.5,
    hop_requested REAL DEFAULT 0.0,
    hop_allocated REAL DEFAULT 0.0,
    location      TEXT,
    metadata      TEXT,
    created_at    TEXT NOT NULL,
    updated_at    TEXT NOT NULL,
    FOREIGN KEY (owner_id) REFERENCES trammers(discord_user_id)
);

CREATE TABLE entity_updates (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    entity_id     TEXT NOT NULL,
    author_id     TEXT NOT NULL,
    body          TEXT NOT NULL,
    created_at    TEXT NOT NULL,
    FOREIGN KEY (entity_id) REFERENCES entities(id)
);

CREATE TABLE event_rsvps (
    event_id      TEXT NOT NULL,
    trammer_id    TEXT NOT NULL,
    status        TEXT NOT NULL,
    PRIMARY KEY (event_id, trammer_id)
);

CREATE TABLE events (
    id            TEXT PRIMARY KEY,
    organizer_id  TEXT NOT NULL,
    title         TEXT NOT NULL,
    starts_at     TEXT,
    duration_min  INTEGER,
    location      TEXT,
    min_attendees INTEGER DEFAULT 1,
    max_attendees INTEGER,
    status        TEXT DEFAULT 'proposed',
    metadata      TEXT,
    created_at    TEXT NOT NULL
);

CREATE TABLE game_weeks (
    week_id       TEXT PRIMARY KEY,
    starts_at     TEXT NOT NULL,
    invest_end    TEXT NOT NULL,
    hop_created   REAL DEFAULT 0.0,
    growth_factor REAL DEFAULT 1.20,
    influence_min REAL DEFAULT 5.0,
    influence_max REAL DEFAULT 100.0,
    aum_per_trammer REAL DEFAULT 5.0,
    status        TEXT DEFAULT 'open'
);

CREATE TABLE hop_placements (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    week_id       TEXT NOT NULL,
    trammer_id    TEXT NOT NULL,
    entity_id     TEXT NOT NULL,
    hop_amount    REAL NOT NULL CHECK(hop_amount > 0),
    placed_at     TEXT NOT NULL,
    UNIQUE (week_id, trammer_id, entity_id)
);

CREATE TABLE hop_recognitions (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    week_id       TEXT,
    entity_id     TEXT NOT NULL,
    trammer_id    TEXT NOT NULL,
    hop_amount    REAL NOT NULL CHECK(hop_amount > 0),
    description   TEXT,
    validated     INTEGER DEFAULT 0,
    created_at    TEXT NOT NULL
);

CREATE TABLE identity_links (
    user_id_a     TEXT NOT NULL,
    user_id_b     TEXT NOT NULL,
    linked_by     TEXT NOT NULL,
    created_at    TEXT NOT NULL,
    PRIMARY KEY (user_id_a, user_id_b),
    CHECK (user_id_a < user_id_b)
);

CREATE TABLE jurisprudence (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    tribunal_id   TEXT NOT NULL,
    summary       TEXT NOT NULL,
    created_at    TEXT NOT NULL
);

CREATE TABLE member_aliases (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id       TEXT NOT NULL,
    name          TEXT NOT NULL,
    first_seen    TEXT NOT NULL,
    last_seen     TEXT NOT NULL,
    is_current    INTEGER NOT NULL DEFAULT 0,
    UNIQUE (user_id, name)
);

CREATE TABLE signalements (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    reporter_id   TEXT NOT NULL,
    target_id     TEXT,
    level         INTEGER NOT NULL,
    description   TEXT NOT NULL,
    status        TEXT DEFAULT 'open',
    created_at    TEXT NOT NULL
);

CREATE TABLE social_norms (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    key           TEXT NOT NULL UNIQUE,
    value         TEXT NOT NULL,
    updated_by    TEXT,
    updated_at    TEXT NOT NULL
);

CREATE TABLE team_members (
    team_id       TEXT NOT NULL,
    trammer_id    TEXT NOT NULL,
    joined_at     TEXT NOT NULL,
    PRIMARY KEY (team_id, trammer_id)
);

CREATE TABLE teams (
    id            TEXT PRIMARY KEY,
    name          TEXT,
    created_at    TEXT NOT NULL
);

CREATE TABLE trammers (
    discord_user_id   TEXT PRIMARY KEY,
    display_name      TEXT,
    locale            TEXT DEFAULT 'fr',
    sponsor_id        TEXT,
    trust_score       REAL DEFAULT 0.0,
    hop_balance       REAL DEFAULT 0.0 CHECK(hop_balance >= 0.0 AND hop_balance <= 99999.99),
    is_tramicien      INTEGER DEFAULT 0,
    created_at        TEXT NOT NULL,
    updated_at        TEXT NOT NULL, profile_json TEXT,
    FOREIGN KEY (sponsor_id) REFERENCES trammers(discord_user_id)
);

CREATE TABLE tribunal_jurors (
    tribunal_id   TEXT NOT NULL,
    trammer_id    TEXT NOT NULL,
    selected_at   TEXT NOT NULL,
    PRIMARY KEY (tribunal_id, trammer_id)
);

CREATE TABLE tribunals (
    id            TEXT PRIMARY KEY,
    signalement_id INTEGER,
    status        TEXT DEFAULT 'mediation',
    decision      TEXT,
    created_at    TEXT NOT NULL
);

CREATE TABLE user_model_prefs (
    discord_user_id   TEXT PRIMARY KEY,
    model             TEXT NOT NULL,
    updated_at        TEXT NOT NULL
);

CREATE TABLE volios (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    trammer_id    TEXT NOT NULL,
    kind          TEXT NOT NULL,
    label         TEXT NOT NULL,
    details       TEXT,
    visibility    TEXT DEFAULT 'network',
    active        INTEGER DEFAULT 1,
    created_at    TEXT NOT NULL,
    FOREIGN KEY (trammer_id) REFERENCES trammers(discord_user_id)
);

CREATE TABLE vote_ballots (
    vote_id       TEXT NOT NULL,
    trammer_id    TEXT NOT NULL,
    choice        TEXT NOT NULL,
    cast_at       TEXT NOT NULL,
    PRIMARY KEY (vote_id, trammer_id)
);

CREATE TABLE votes (
    id            TEXT PRIMARY KEY,
    title         TEXT NOT NULL,
    description   TEXT,
    threshold     REAL DEFAULT 0.80,
    created_by    TEXT NOT NULL,
    status        TEXT DEFAULT 'open',
    closes_at     TEXT,
    created_at    TEXT NOT NULL
);

CREATE TABLE web_sources (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    seed_url         TEXT NOT NULL UNIQUE,
    domain           TEXT NOT NULL,
    label            TEXT,
    max_depth        INTEGER NOT NULL DEFAULT 2,
    max_pages        INTEGER NOT NULL DEFAULT 25,
    added_by         TEXT NOT NULL,
    added_at         TEXT NOT NULL,
    last_indexed_at  TEXT,
    last_page_count  INTEGER DEFAULT 0,
    last_chunk_count INTEGER DEFAULT 0,
    last_error       TEXT,
    active           INTEGER NOT NULL DEFAULT 1
);

CREATE INDEX idx_channel_todos_channel ON channel_todos(channel_id);
