#!/usr/bin/env python3
"""Dump the SQLite schema the bot actually creates into ``docs/design/schema.sql``.

The DDL in ``storage/db.py`` is the source of truth. This script bootstraps both
databases in a temporary directory, reads ``sqlite_master`` back, and writes the
result so the data-model documentation includes it instead of copying it.

Usage:
    python scripts/dump_schema.py            # rewrite docs/design/schema.sql
    python scripts/dump_schema.py --check    # exit 1 if the file is out of date
"""

from __future__ import annotations

import sqlite3
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from storage.db import Database  # noqa: E402

OUT = ROOT / "docs" / "design" / "schema.sql"
HEADER = (
    "-- Generated by scripts/dump_schema.py from storage/db.py. Do not edit by hand;\n"
    "-- run `python scripts/dump_schema.py` after changing the schema.\n"
)


def _dump(conn: sqlite3.Connection, name: str) -> str:
    rows = conn.execute(
        "SELECT type, name, sql FROM sqlite_master "
        "WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' "
        "ORDER BY CASE type WHEN 'table' THEN 0 ELSE 1 END, name"
    ).fetchall()
    out = [f"\n-- ==== {name} " + "=" * (70 - len(name)) + "\n"]
    for row in rows:
        out.append(f"{row['sql']};\n")
    return "\n".join(out)


def render() -> str:
    with tempfile.TemporaryDirectory() as tmp:
        db = Database(Path(tmp) / "app.sqlite", Path(tmp) / "history.sqlite")
        try:
            db.init_schema()
            text = HEADER + _dump(db.history, "history.sqlite") + _dump(db.app, "app.sqlite")
        finally:
            db.close()
    return text


def main(argv: list[str]) -> int:
    text = render()
    if "--check" in argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"{OUT.relative_to(ROOT)} is out of date; run scripts/dump_schema.py", file=sys.stderr)
            return 1
        print("schema.sql is up to date")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
